package com.cglia.hibernate.reversebean;
// Generated Aug 4, 2023, 9:49:41 AM by Hibernate Tools 6.0.2.Final

/**
 * Addtrain generated by hbm2java
 */
public class Addtrain implements java.io.Serializable {

	private int trainnumber;
	private String trainname;
	private String startingstation;
	private String endingstation;
	private String starttime;
	private String endtime;
	private String duration;
	private Integer rupees;

	public Addtrain() {
	}

	public Addtrain(int trainnumber, String startingstation, String endingstation) {
		this.trainnumber = trainnumber;
		this.startingstation = startingstation;
		this.endingstation = endingstation;
	}

	public Addtrain(int trainnumber, String trainname, String startingstation, String endingstation, String starttime,
			String endtime, String duration, Integer rupees) {
		this.trainnumber = trainnumber;
		this.trainname = trainname;
		this.startingstation = startingstation;
		this.endingstation = endingstation;
		this.starttime = starttime;
		this.endtime = endtime;
		this.duration = duration;
		this.rupees = rupees;
	}

	public int getTrainnumber() {
		return this.trainnumber;
	}

	public void setTrainnumber(int trainnumber) {
		this.trainnumber = trainnumber;
	}

	public String getTrainname() {
		return this.trainname;
	}

	public void setTrainname(String trainname) {
		this.trainname = trainname;
	}

	public String getStartingstation() {
		return this.startingstation;
	}

	public void setStartingstation(String startingstation) {
		this.startingstation = startingstation;
	}

	public String getEndingstation() {
		return this.endingstation;
	}

	public void setEndingstation(String endingstation) {
		this.endingstation = endingstation;
	}

	public String getStarttime() {
		return this.starttime;
	}

	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	public String getEndtime() {
		return this.endtime;
	}

	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}

	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public Integer getRupees() {
		return this.rupees;
	}

	public void setRupees(Integer rupees) {
		this.rupees = rupees;
	}

}
