package com.cglia.hibernate.reversebean;
// Generated Aug 4, 2023, 9:49:41 AM by Hibernate Tools 6.0.2.Final

/**
 * Post generated by hbm2java
 */
public class Post implements java.io.Serializable {

	private int id;

	public Post() {
	}

	public Post(int id) {
		this.id = id;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

}
