package com.cglia.hibernate.reversebean;
// Generated Aug 4, 2023, 9:49:41 AM by Hibernate Tools 6.0.2.Final

/**
 * StudentProjectTable generated by hbm2java
 */
public class StudentProjectTable implements java.io.Serializable {

	private StudentProjectTableId id;

	public StudentProjectTable() {
	}

	public StudentProjectTable(StudentProjectTableId id) {
		this.id = id;
	}

	public StudentProjectTableId getId() {
		return this.id;
	}

	public void setId(StudentProjectTableId id) {
		this.id = id;
	}

}
