package com.cglia.hibernate.reversebean;
// Generated Aug 4, 2023, 9:49:41 AM by Hibernate Tools 6.0.2.Final

/**
 * StudentProjectInformation generated by hbm2java
 */
public class StudentProjectInformation implements java.io.Serializable {

	private int projectId;
	private String dateOfFinish;
	private String projectName;

	public StudentProjectInformation() {
	}

	public StudentProjectInformation(int projectId) {
		this.projectId = projectId;
	}

	public StudentProjectInformation(int projectId, String dateOfFinish, String projectName) {
		this.projectId = projectId;
		this.dateOfFinish = dateOfFinish;
		this.projectName = projectName;
	}

	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public String getDateOfFinish() {
		return this.dateOfFinish;
	}

	public void setDateOfFinish(String dateOfFinish) {
		this.dateOfFinish = dateOfFinish;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
