package com.cglia.hibernate.reversebean;
// Generated Aug 4, 2023, 9:49:41 AM by Hibernate Tools 6.0.2.Final

/**
 * StudentInformation generated by hbm2java
 */
public class StudentInformation implements java.io.Serializable {

	private int studentId;
	private String studentEmail;
	private String studentGender;
	private String studentName;
	private Integer resultId;

	public StudentInformation() {
	}

	public StudentInformation(int studentId) {
		this.studentId = studentId;
	}

	public StudentInformation(int studentId, String studentEmail, String studentGender, String studentName,
			Integer resultId) {
		this.studentId = studentId;
		this.studentEmail = studentEmail;
		this.studentGender = studentGender;
		this.studentName = studentName;
		this.resultId = resultId;
	}

	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	public String getStudentEmail() {
		return this.studentEmail;
	}

	public void setStudentEmail(String studentEmail) {
		this.studentEmail = studentEmail;
	}

	public String getStudentGender() {
		return this.studentGender;
	}

	public void setStudentGender(String studentGender) {
		this.studentGender = studentGender;
	}

	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	public Integer getResultId() {
		return this.resultId;
	}

	public void setResultId(Integer resultId) {
		this.resultId = resultId;
	}

}
