package com.cglia.hibernate.reversebean;
// Generated Aug 4, 2023, 9:49:41 AM by Hibernate Tools 6.0.2.Final

/**
 * StudentAddress generated by hbm2java
 */
public class StudentAddress implements java.io.Serializable {

	private int addressId;
	private String city;
	private String state;
	private String typeOfAddress;
	private Integer studentId;

	public StudentAddress() {
	}

	public StudentAddress(int addressId) {
		this.addressId = addressId;
	}

	public StudentAddress(int addressId, String city, String state, String typeOfAddress, Integer studentId) {
		this.addressId = addressId;
		this.city = city;
		this.state = state;
		this.typeOfAddress = typeOfAddress;
		this.studentId = studentId;
	}

	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getTypeOfAddress() {
		return this.typeOfAddress;
	}

	public void setTypeOfAddress(String typeOfAddress) {
		this.typeOfAddress = typeOfAddress;
	}

	public Integer getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

}
