package com.cglia.hibernate.reversebean;
// Generated Aug 4, 2023, 9:49:41 AM by Hibernate Tools 6.0.2.Final

/**
 * StudentProjectTableId generated by hbm2java
 */
public class StudentProjectTableId implements java.io.Serializable {

	private int projectId;
	private int studentId;

	public StudentProjectTableId() {
	}

	public StudentProjectTableId(int projectId, int studentId) {
		this.projectId = projectId;
		this.studentId = studentId;
	}

	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudentProjectTableId))
			return false;
		StudentProjectTableId castOther = (StudentProjectTableId) other;

		return (this.getProjectId() == castOther.getProjectId()) && (this.getStudentId() == castOther.getStudentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProjectId();
		result = 37 * result + this.getStudentId();
		return result;
	}

}
