package com.cglia.hibernate.reversebean;
// Generated Aug 4, 2023, 9:49:41 AM by Hibernate Tools 6.0.2.Final

/**
 * TicketbookId generated by hbm2java
 */
public class TicketbookId implements java.io.Serializable {

	private Integer age;
	private String date;
	private String email;
	private String endingstation;
	private String gender;
	private String mobileNo;
	private String name;
	private String startingstation;
	private int trainnumber;

	public TicketbookId() {
	}

	public TicketbookId(int trainnumber) {
		this.trainnumber = trainnumber;
	}

	public TicketbookId(Integer age, String date, String email, String endingstation, String gender, String mobileNo,
			String name, String startingstation, int trainnumber) {
		this.age = age;
		this.date = date;
		this.email = email;
		this.endingstation = endingstation;
		this.gender = gender;
		this.mobileNo = mobileNo;
		this.name = name;
		this.startingstation = startingstation;
		this.trainnumber = trainnumber;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getEndingstation() {
		return this.endingstation;
	}

	public void setEndingstation(String endingstation) {
		this.endingstation = endingstation;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getStartingstation() {
		return this.startingstation;
	}

	public void setStartingstation(String startingstation) {
		this.startingstation = startingstation;
	}

	public int getTrainnumber() {
		return this.trainnumber;
	}

	public void setTrainnumber(int trainnumber) {
		this.trainnumber = trainnumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TicketbookId))
			return false;
		TicketbookId castOther = (TicketbookId) other;

		return ((this.getAge() == castOther.getAge())
				|| (this.getAge() != null && castOther.getAge() != null && this.getAge().equals(castOther.getAge())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getEndingstation() == castOther.getEndingstation())
						|| (this.getEndingstation() != null && castOther.getEndingstation() != null
								&& this.getEndingstation().equals(castOther.getEndingstation())))
				&& ((this.getGender() == castOther.getGender()) || (this.getGender() != null
						&& castOther.getGender() != null && this.getGender().equals(castOther.getGender())))
				&& ((this.getMobileNo() == castOther.getMobileNo()) || (this.getMobileNo() != null
						&& castOther.getMobileNo() != null && this.getMobileNo().equals(castOther.getMobileNo())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getStartingstation() == castOther.getStartingstation())
						|| (this.getStartingstation() != null && castOther.getStartingstation() != null
								&& this.getStartingstation().equals(castOther.getStartingstation())))
				&& (this.getTrainnumber() == castOther.getTrainnumber());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAge() == null ? 0 : this.getAge().hashCode());
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getEndingstation() == null ? 0 : this.getEndingstation().hashCode());
		result = 37 * result + (getGender() == null ? 0 : this.getGender().hashCode());
		result = 37 * result + (getMobileNo() == null ? 0 : this.getMobileNo().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getStartingstation() == null ? 0 : this.getStartingstation().hashCode());
		result = 37 * result + this.getTrainnumber();
		return result;
	}

}
