package com.cglia.hibernate.reversebean;
// Generated Aug 4, 2023, 9:49:41 AM by Hibernate Tools 6.0.2.Final

/**
 * Ticketbook generated by hbm2java
 */
public class Ticketbook implements java.io.Serializable {

	private TicketbookId id;

	public Ticketbook() {
	}

	public Ticketbook(TicketbookId id) {
		this.id = id;
	}

	public TicketbookId getId() {
		return this.id;
	}

	public void setId(TicketbookId id) {
		this.id = id;
	}

}
